export type Page={slug:string;title:string;h1:string;description:string;kind:string;answer:string;checks?:string[];related:string[];commercial?:boolean};
export const ORIGIN=process.env.NEXT_PUBLIC_SITE_URL||"https://uk-vpn-guide.example";
export const affiliates={adguard:{path:"/go/adguard/",destination:null},vpn:{path:"/go/adguard-vpn/",destination:null},dns:{path:"/go/adguard-dns/",destination:null}} as const;
const core:Page[]=[
["adguard-products","AdGuard VPN vs Ad Blocker vs DNS","AdGuard VPN vs Ad Blocker vs DNS: which product do you need?","Choose VPN for encryption and IP/location use cases, Ad Blocker for device filtering, and DNS for network-level domain rules.","commercial",true],
["adguard-vpn-review-uk","AdGuard VPN Review for UK Users","AdGuard VPN review for UK users: features, limits and value","Our top VPN pick for UK users who want a VPN that works as part of the wider AdGuard privacy suite.","commercial",true],
["adguard-ad-blocker-review","AdGuard Ad Blocker Review","AdGuard Ad Blocker review: device-wide blocking, apps and licence options","Our top pick for device-wide ad and tracker blocking; capabilities differ by platform.","commercial",true],
["adguard-dns-review","AdGuard DNS Review","AdGuard DNS review: network-wide filtering, privacy and plan limits","Our top pick for configurable network-wide DNS filtering; DNS does not replace a VPN.","commercial",true],
["best-vpn-uk","Best VPNs for the UK","Best VPNs for the UK: compared on privacy and everyday use","AdGuard VPN leads for AdGuard-suite integration, but no unsupported speed or streaming winner is named.","comparison",true],
["best-free-vpn-uk","Best Free VPN Options UK","Best free VPN options for UK users — limits, risks and safer alternatives","AdGuard VPN Free suits light use: 3 GB monthly, four locations, two devices and no free streaming servers.","comparison",true],
["is-vpn-legal-uk","Are VPNs Legal in the UK?","Are VPNs legal in the UK? What the law does and does not prohibit","VPNs are legal in the UK. A VPN does not legalise unlawful conduct or override service terms.","legal",false],
["vpn-reviews","UK VPN Reviews","UK VPN reviews: how providers compare and what we verify","Only AdGuard VPN has a full launch review; no unsupported provider reviews or scores are fabricated.","comparison",false],
["vpn-comparisons","Compare VPN Services UK","Compare VPN services for UK use","Compare documented capability separately from observed performance and service-access tests.","comparison",true],
["vpn-for-gaming","Best VPNs for Gaming UK","Best VPNs for gaming in the UK: latency, stability and setup compared","A VPN may improve a poor route or add overhead; measure ping, jitter and packet loss before deciding.","use case",true],
["vpn-for-streaming","Best VPNs for Streaming UK","Best VPNs for streaming in the UK: services, devices and limitations","Streaming access changes; no service winner is claimed without a dated observed test.","use case",true],
["vpn-for-bbc-iplayer","VPNs for BBC iPlayer","VPNs for BBC iPlayer: UK access, testing notes and troubleshooting","No current AdGuard access result is claimed. BBC iPlayer requires a TV Licence on any device.","use case",true],
["vpn-for-netflix","VPNs for Netflix UK","VPNs for Netflix UK: availability, speed and troubleshooting","No current UK catalogue result is claimed; Netflix documents VPN-related catalogue and plan limitations.","use case",true],
["vpn-for-travel","Best VPNs for UK Travellers","Best VPNs for UK travellers: public Wi-Fi, roaming and access abroad","AdGuard VPN supports up to ten paid devices, but travellers must check local rules at each destination.","use case",true]
].map(x=>({slug:x[0] as string,title:x[1] as string,h1:x[2] as string,description:x[3] as string,answer:x[3] as string,kind:x[4] as string,commercial:x[5] as boolean,related:["/best-vpn-uk/","/how-we-test-vpns/","/affiliate-disclosure/"]}));
const deviceNames=[["vpn-for-windows","Windows"],["vpn-for-mac","Mac"],["vpn-for-iphone","iPhone"],["vpn-for-android","Android"],["vpn-for-router","routers"]];
const devices:Page[]=deviceNames.map(([slug,name])=>({slug,title:`VPN for ${name}: UK Guide`,h1:`VPN for ${name}: setup, privacy and common problems`,description:`Evidence-led VPN setup and troubleshooting for ${name}.`,kind:"device",answer:`Confirm documented ${name} support, record existing network settings, then test the connection before relying on it.`,checks:["Update the device or firmware","Disable conflicting VPN profiles for a controlled test","Test a nearby location","Confirm DNS and firewall settings"],related:["/adguard-vpn-review-uk/","/vpn-not-working/","/best-vpn-uk/"],commercial:true}));
const troubleDefs=[
["vpn-not-connecting","VPN not connecting","Network, protocol, location or security-software conflicts commonly prevent the tunnel opening."],
["vpn-connected-no-internet","VPN connected but no internet","DNS, captive portals and stale routes can break traffic after the tunnel opens."],
["vpn-keeps-disconnecting","VPN keeps disconnecting","Unstable networks, mobile handover and battery restrictions cause repeated disconnects."],
["vpn-connection-drops","VPN connection drops","Short drops can expose weak Wi-Fi or aggressive power management."],
["vpn-slow","VPN slow","Compare the same connection with and without VPN before blaming encryption or routing."],
["vpn-not-working","VPN not working","Identify whether the fault affects the app, tunnel, internet, one service or the account."],
["vpn-not-working-windows","VPN not working on Windows","Check adapters, firewall rules, DNS and competing VPN clients."],
["vpn-not-working-mac","VPN not working on Mac","Check network extensions, content filters and old VPN profiles."],
["vpn-not-working-iphone","VPN not working on iPhone","Check the VPN profile, portal sign-in, Low Power Mode and network restrictions."],
["vpn-not-working-android","VPN not working on Android","Check battery optimisation, Private DNS and always-on VPN settings."],
["adguard-vpn-login-problems","AdGuard VPN login problems","Separate account access from connection faults before changing network settings."],
["adguard-vpn-password-reset","AdGuard VPN password reset","Use one official reset request and the newest delivered link."],
["adguard-account-verification","AdGuard account verification issues","Incorrect addresses, filtering, expired links and delivery delays are common causes."],
["adguard-verification-code-not-received","AdGuard verification code not received","Check delivery and account details before requesting repeated codes."]];
const trouble:Page[]=troubleDefs.map(([slug,name,answer])=>({slug,title:`${name}: Fixes`,h1:`${name}: causes and fixes`,description:`Quick checks and ordered fixes for ${name.toLowerCase()}.`,kind:"troubleshooting",answer,checks:["Confirm ordinary internet access","Restart the app and device","Change one variable at a time","Try a nearby location or trusted network","Check official status and support if several devices fail"],related:["/vpn-not-working/","/vpn-not-connecting/","/vpn-connected-no-internet/"]}));
const trustDefs=[["about","About UK VPN Guide","This is an independent publisher and is not operated by AdGuard."],["how-we-test-vpns","How We Test VPNs","We separate official documentation, provider claims, observed tests and editorial judgement."],["editorial-policy","Editorial Policy","Primary sources, visible limitations and dated updates guide editorial decisions."],["corrections-policy","Corrections Policy","Material factual corrections are dated and explained."],["affiliate-disclosure","Affiliate Disclosure","We may earn a commission if you buy through our links. This does not affect our editorial assessment."],["contact","Contact","Owner contact details must be configured before public launch; never send passwords or codes."],["privacy-policy","Privacy Policy","This static launch build has no user accounts or behavioural advertising scripts."],["terms","Terms of Use","Content is general information and product terms can change."]];
const trust:Page[]=trustDefs.map(([slug,h1,answer])=>({slug,title:`${h1} | UK VPN Guide`,h1,description:answer,answer,kind:"trust",related:["/about/","/editorial-policy/","/how-we-test-vpns/"]}));
export const pages=[...core,...devices,...trouble,...trust];
export const bySlug=new Map(pages.map(p=>[p.slug,p]));
